### ISSUE TITLE
You cannot safely chain gitignore files.

### ISSUE THREAD

**Issue by DavidJFelix** [iepathos/gitignore#1]
A gitignore file uses a "last rule wins" policy meaning the order of rules makes a huge difference in how the rules are applied. Suppose you have a `gradle` gitignore which explicitly allows the gradle wrapper jar to be included in source (this is common):

```
!gradle-wrapper.jar
```

then you have a `java` gitignore which will not want to include jars as a default behavior since they are binary files. Including gradle wrapper is fine because it never changes, but build artifacts will and you may not be using gradle... so your java gitignore looks like

```
*.jar
```

If you invoke your tool using `gitignore java gradle` the tool works as expected (in this case) but `gitignore gradle java` will mean that the java rule wins and your gradle wrapper jar will be ignored.

The above case is one of the most notable cases but the point is that there could be any number of these cases across any permutation of gitignore files and order, but you won't know because they utilize regex matching. Each of these files is a tested, closed and reliable gitignore, but combining them will not yield a correct, tested and reliable gitignore file.

One potential way to fix this might be to group sections of the gitignore and attempt to figure out how to stitch 2 together, or create a bunch of rules for combining them -- but this seems like a lot of legwork.

My suggestion would be to simply warn users that they may not get a good gitignore by listing all of the technology in their project -- in fact they may get a bad gitignore because it's verbose, autogenerated and not understood by any user who put it into git.

I'm not fun at parties.

**Comment by iepathos** [comment]
Hello, thanks for pointing this out!  I generally chain an OS with the language I'm using so something like gitignore macos python

While I haven't run into this conflict yet, it definitely exists and is an interesting problem.  So, while I wanted to keep this tool simple, it also happens to be a tool I have ended up using a lot so I don't mind putting in extra legwork to eliminate possible .gitignore pattern conflicts.

I will try to create a fix and will post the warning in the README in the meantime.

**Comment by iepathos** [comment]
Fixed conflicts for * and ! .gitignore entries being chained together.  Not sure all possible pattern conflicts are fixed for this but it will print any patterns that match each other.  Please open up another issue if you find another conflict example chaining any of the hosted gitignores and I will try to fix.
